ボウリングのスコア計算プログラムを作成しました
ksmxxxxxx/ruby-practices pull request #1
Opened 2021-01-19 02:26 UTC by ksmxxxxxx

# 概要

ボウリングのスコア計算プログラムを作成しました。

# やったこと

- スコア計算プログラムの作成
- プログラムのクラスの計算メソッド毎のテスト
  - テストパターンは[プラクティスページ](https://bootcamp.fjord.jp/practices/210)の例をテストするようにしています
- ターミナルでの実行結果をスクリーンショット

# 特にレビューしてほしいと思っているポイント

- メソッドの分割
  - RubocopのLint結果を参考に、なるべく意味のある単位になるように分割した（が、これで方向性としてあってるのか？）
- Gameクラスの処理
  - 条件分岐がかなり複雑になってしまったのが気になっています。
  - もしかしたら`add_zero_when_strike`メソッドの処理しなくてもいいのでは？とひととおり作ってから考えたのですが、これをしないと10フレーム目の計算とかが合わなかったとか……何か理由があってこの処理を入れているんですが、作った当初から時間が経ちすぎてて入れた理由が思い出せず…。

# Screenshot (Terminal result)
<img width="303" alt="スクリーンショット 2021-01-19 11 03 53" src="https://user-images.githubusercontent.com/5976902/104979091-c8eb3380-5a46-11eb-86de-8d9bda5f8951.png">

2021-01-22 12:26 UTC, torinoko requested changes
気になったところをコメントしました。
コードも増えてきましたし、クラスごとにファイルを分けてみてもいいかもですね。

> メソッドの分割
> RubocopのLint結果を参考に、なるべく意味のある単位になるように分割した（が、これで方向性としてあってるのか？）

「なるべく意味のある単位」を考慮したのはとてもよいですね！
方向性は大丈夫だと思います。

> Gameクラスの処理
> 条件分岐がかなり複雑になってしまったのが気になっています。

「複雑さが気になる」という感覚はすごくいいですね。
私も気になってます！
個別のコメントにも書きましたが、変数や処理で見直せそうなポイントがありますね。

> 何か理由があってこの処理を入れているんですが

お、ここの理由ははっきりさせたい気がしますね！
はっきりしない処理のせいで、複雑さが増している可能性もあります。
あと、コードはこの後メンテナンスされるかもしれないですよね。
そのとき毎回「これ何だっけ？」って考えるのは面倒ですよね。
面倒なことは今のうちに片付けちゃいましょう！

2021-01-22 12:26 UTC, torinoko commented on 07.bowling_object/lib/bowling.rb
> +    frames.size
ここの行はどんな意図で入れていますか？

2021-01-22 12:26 UTC, torinoko commented on 07.bowling_object/lib/bowling.rb
> +      add_frame_score(frames, num)
メソッド名が `add_frame_score` で `frame` が単数系ですが、渡しているのは `flames` で複数なんですね。命名の分かりやすさはもう少し上げることができそうな気がします。

2021-01-22 12:26 UTC, torinoko commented on 07.bowling_object/lib/bowling.rb
> +    all_score.sum
`@all_score` は最終的にここで合計するんですね。
`@all_score` をインスタンス変数にするメリットってどんなところでしょう？

2021-01-22 12:26 UTC, torinoko commented on 07.bowling_object/lib/bowling.rb
> +                 end
これは好みの問題なのですが、`if` の戻り値を変数に代入するような書き方はあまりしないです。
一般的ではないので読み手がちょっとがんばらなくちゃいけないかな？

2021-01-22 12:26 UTC, torinoko commented on 07.bowling_object/lib/bowling.rb
> +                 end
引数の `frames` と `num` ですが、メソッドの中でまた次のメソッドに渡され続けているのがちょっと気になりますね。
特に `frames` はインスタンス変数にもなので、全体的にもう少しすっきりさせることができそうな気がします。

2021-01-22 12:26 UTC, torinoko commented on 07.bowling_object/lib/bowling.rb
> +    end
`if` の中に `if` がある（ `if` がネストしているとも言いますね :)）のは、コードをよくできる可能性のあるところです。
メソッドに切り出せたり、処理をコンパクトにできるかも？

`Frame.new` がたくさん登場しているのも、重複している処理があるということなので改善チャンスがありそうです。

ぜひ考えてみてください〜！

2021-01-22 12:26 UTC, torinoko commented on 07.bowling_object/lib/bowling.rb
> +    end
ここもそうですね！

2021-01-22 12:26 UTC, torinoko commented on 07.bowling_object/lib/bowling.rb
> +  end
ここでは具体的にどんな処理をしているんでしょうか？
`map` メソッドについても見直してみるといいかもしれません。

2021-01-22 12:26 UTC, torinoko commented on 07.bowling_object/lib/bowling.rb
> +  end
`add_zero_when_strike` というメソッド名に比べるといろんな処理が入っていますね。
最後にインスタンス変数の `@shots`を返していますが、ここでしか使ってないかな？
インスタンス変数と、メソッド内でのみ使う変数を分けて使えるとよさそうですね。

2021-01-22 12:26 UTC, torinoko commented on 07.bowling_object/lib/bowling.rb
> +  end
スペアは「1投目で残ったピンを2投目で全部倒すと10点」なんですね〜。
これだとストライクも `spare?` で `true` を返しちゃいますね。
ストライクのときは `false` を返せるとよさそうですね。

2021-01-22 12:26 UTC, torinoko commented on 07.bowling_object/lib/bowling.rb
> +    mark.to_i
このくらいであれば三項演算子を使ってもいいかもしれませんね。
（好みの問題ですし、三項演算子を嫌う人もいるのでどちらでも〜！）
```
mark.include?('X') ? 10 : mark.to_i
```

2021-01-23 15:11 UTC, ksmxxxxxx commented on 07.bowling_object/lib/bowling.rb
> +                 end
> これは好みの問題なのですが、if の戻り値を変数に代入するような書き方はあまりしないです。
一般的ではないので読み手がちょっとがんばらなくちゃいけないかな？

https://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Style/ConditionalAssignment

こちらはRubocopのLintに合わせて書いたものになります。
デフォルトの設定だと警告が出るパターンだったのですが、fjordのrubocopは警告出さないようになってるんですかね？
（提出した時rubocopは通してたんですが、先日rubyにインストールされてるrubocopがfjordのものじゃなかった可能性があることが一昨夜発覚しました…）

2021-01-23 15:23 UTC, ksmxxxxxx commented on 07.bowling_object/lib/bowling.rb
> +                 end
あー……っていうより、if分の部分をメソッドとかにしてしまって、変数にメソッドを代入するって意図ですかね？

2021-01-23 22:48 UTC, ksmxxxxxx commented on 07.bowling_object/lib/bowling.rb
> +    frames.size
多分作り途中の確認用コードの名残ですね……削除します。

2021-01-24 02:15 UTC, torinoko commented on 07.bowling_object/lib/bowling.rb
> +                 end
そうですね、処理が短ければ三項演算子で、長くなりそうであればメソッドにするなどの対応をとることが多いですね！

2021-01-24 03:49 UTC, ksmxxxxxx commented on 07.bowling_object/lib/bowling.rb
> +    mark.to_i
Fixed
https://github.com/ksmxxxxxx/ruby-practices/pull/1/commits/f2768285a771f24897602830b27ecd34018ebbf9

2021-01-24 03:50 UTC, ksmxxxxxx commented on 07.bowling_object/lib/bowling.rb
> +                 end
Fixed
https://github.com/ksmxxxxxx/ruby-practices/pull/1/commits/f2768285a771f24897602830b27ecd34018ebbf9

2021-01-24 03:52 UTC, ksmxxxxxx commented on 07.bowling_object/lib/bowling.rb
> +      add_frame_score(frames, num)
Fixed
a5861e01fcde996ed3c76e592e2039a9d4ba03f1

2021-01-24 03:58 UTC, ksmxxxxxx commented on 07.bowling_object/lib/bowling.rb
> +    frames.size
🚮 https://github.com/ksmxxxxxx/ruby-practices/pull/1/commits/11ce4643f14817497342510498572991f7ee840c

2021-01-24 05:23 UTC, ksmxxxxxx commented on 07.bowling_object/lib/bowling.rb
> +    all_score.sum
Fixed
42e9b189a0de2b1bbbbe27ede4dd816aea48ee34

メソッド間で配列を渡すためにインスタンス変数にしていたんですが、2つのメソッドでしか使ってなかったし、 `score`メソッドの中で計算するために配列に入れていってるだけなので、`score`メソッドの中のローカル変数に `[]`を作って上げて、そこにどんどこ追加して`sum`すでば良いかと思ってこの変更をしました。

指摘意図、あってたでしょうか？

2021-01-24 06:18 UTC, ksmxxxxxx commented on 07.bowling_object/lib/bowling.rb
> +    end
Fixed
3659f4eb6c037951d9b5f3803181b055e1c2fb97

意図が組めてるかわかりませんが、こういうことかなという修正をしてみました。

2021-01-24 06:19 UTC, ksmxxxxxx commented on 07.bowling_object/lib/bowling.rb
> +    end
Fixed
3659f4eb6c037951d9b5f3803181b055e1c2fb97

2021-01-24 06:53 UTC, ksmxxxxxx commented on 07.bowling_object/lib/bowling.rb
> +  end
Fixed
ac96fc43d59dd47b7a2758cfd53dc5e77eaa275e

2021-01-24 13:09 UTC, ksmxxxxxx commented on 07.bowling_object/lib/bowling.rb
> +  end
Fixed
6661a9a

2021-01-25 12:39 UTC, ksmxxxxxx commented on 07.bowling_object/lib/bowling.rb
> +  end
作ったフレームを1フレーム2投にするための処理だったんですが、必要なかったのでこの処理はなくしました。
8096d8e

2021-01-25 12:41 UTC, ksmxxxxxx commented on 07.bowling_object/lib/bowling.rb
> +  end
`X`の時、`0`を挿入するものでしたが、そもそも入れなくても計算できるなと思ったので、変更しました。
8096d8e

2021-01-25 12:42 UTC, ksmxxxxxx commented
> コードも増えてきましたし、クラスごとにファイルを分けてみてもいいかもですね。

2639cb4

ここでファイルを分割しました。

2021-01-26 04:00 UTC, torinoko approved these changes
@ksmxxxxxx 
よいと思います！
見通しのよいコードになりましたね ✨ 
`spare?` だけ修正必要そうですが、全体的にはよさそうなので Approve しますね！

2021-01-26 04:00 UTC, torinoko commented on 07.bowling_object/lib/frame.rb
> +  end
`strike?` が true のときに何が返るでしょうか？
`?` のついてるメソッドなので、true / false が返るとよいですね 😃

2021-01-26 04:00 UTC, torinoko commented on 07.bowling_object/lib/game.rb
> +  end
ここはこんなふうに書き換えることもできそうですね。
（うーんでも分かりにくくなっちゃうかな……どうだろ……）
```
def frame_is_last
  third_mark = game_frames[num].size == 2 ? '3' : game_frames[num][2]
  Frame.new(game_frames[num][0], game_frames[num][1], third_mark).score
end
```

2021-01-26 07:39 UTC, ksmxxxxxx commented on 07.bowling_object/lib/frame.rb
> +  end
あー、これは私のほうがちょっと勘違いしてました 💦 
`[first_shot.score, second_shot.score].sum == 10`だけだと、`strike?`も通っちゃうから、
`first_shot.score`が`strike?`でfales、かつ`[first_shot.score, second_shot.score].sum == 10`じゃないとspareにならないですね
修正します〜

2021-01-26 07:43 UTC, ksmxxxxxx commented on 07.bowling_object/lib/game.rb
> +  end
これはちょっと迷いますね。
@torinoko さんの案もスッキリしてていいかなぁと思う一方で、パット見が分かりづらいかなぁという気がします。

ちなみに
```
Frame.new(game_frames[num][0], game_frames[num][1], '3').score
```
の最後の`'3'`は、デバック用に適当に3を入れてただけなので、0にしようとし思います。

2021-01-26 08:58 UTC, ksmxxxxxx commented on 07.bowling_object/lib/frame.rb
> +  end
4c4a8f5

こういうことかな…と考えて修正してみました。
が、ちょっとゲシュタルト崩壊気味です……🤪

2021-01-26 09:05 UTC, ksmxxxxxx commented on 07.bowling_object/lib/game.rb
> +  end
7cd8cda

第3引数の数字だけなおして、if文のところはそのままにしました。
pushしたあとに

```
  def frame_is_last
    first_mark = game_frames[num][0]
    second_mark = game_frames[num][1]
    third_mark = game_frames[num].size == 2 ? '0' : game_frames[num][2]
    Frame.new(first_mark, second_mark, third_mark)
  end
```
こういうのだったらもうちょっと見やすいかなぁって考えたんですがどうでしょう？
冗長ですかね？

2021-01-26 10:13 UTC, torinoko commented on 07.bowling_object/lib/frame.rb
> +  end
そうですそうです、完璧ですー！
元のコードだと、 `strike?` が `true` だったときに `nil` が返っちゃうんですよね。

意味のわからないコードで申し訳ないのですが、
下記のようなメソッドを irb 等で実行してみてください。
引数でゼロが渡されたときに `nil` が返ることを確認できると思います。
```
def hoge?(num)
  true unless num.zero?
end
```

なので修正いただいたように、条件の中に `!strike?` を入れてしまうとこれを回避できます。

2021-01-26 10:14 UTC, torinoko commented on 07.bowling_object/lib/game.rb
> +  end
好みはあると思いますが、私は好きです！
一時的にしか使わないとしても、意味のある名前がついた変数に入れるとすごく読みやすくなりますねー。

2021-01-26 14:56 UTC, ksmxxxxxx commented on 07.bowling_object/lib/game.rb
> +  end
ありがとうございます！この方向で修正しておきます〜 👏

2021-01-26 14:59 UTC, ksmxxxxxx commented
`git rebase -i` ed.

2021-01-26 15:17 UTC, merged