Ls command oop
ksmxxxxxx/ruby-practices pull request #2
Opened 2021-02-04 08:14 UTC by ksmxxxxxx

lsコマンドのオブジェクト指向版を作成しました。

# Did

- 非オブジェクト指向版→オブジェクト指向に置き換え
  - ディレクトリ指定
  - ハードリンクのリンクファイル元パス表示
  - ターミナル幅に応じたカラム表示
  - ファイルのタイムスタンプをmacOSに合わせる
- テスト

# Did not to

- ディレクトリ複数対応

# レビューほしいポイント

- コードの中にコメントしている部分について
  - Rubocopに注意されたけど、どう書き直したものかがわからなかった
  - 同じようなことをやっているメソッドがあって、もっと効率的にしたかったけど独力ではうまくいかなくて諦めた
  - [（あなたの周りでも見かけるかもしれない）インスタンス変数の間違った使い方 \- Qiita](https://qiita.com/jnchito/items/49fe82364bca2f4f37f5)を読んでて、一部気になったところがあったが「でもオプションによってインスタンス変数に入ってくる内容が変わってくるからこのままでもいいのかも…」と思ってそのままにしている

# Screenshot

2021-02-09 09:44 UTC, kakutani commented
> Did

Did What? という気持ちになったのですが、どこかで見かける言い回しでしょうか…。「Did not do」も同様で「やってません!」っていう印象を受けました。感性の問題かな…。特に代案もないのですが…。

> ↑macOS

スクショを貼り忘れているのかも?

> * Rubocopに注意されたけど、どう書き直したものかがわからなかった

* rubocopの実行結果があれば教えてください(スクショよりはターミナルへの出力結果がよさそう)
* .rubocop.yml もあるとうれしいです(どういう設定にもとづいた警告だったのかがわかると参考になりそう)

2021-02-09 09:57 UTC, kakutani commented
せっかくテストが書いてあったようなので、実行してみようと思ったのですが成功しませんでした…。
`test/fixtures/dir_foobar` が必要なのかな? と思って作成したら、最初失敗していたものは成功したのですが、
dotfilesを表示するオプションのテストかな? は並び順が私の環境では違うのかな…テストが通りませんでした。

コードはまだ追っていませんが、ファイルやディレクトリのタイムスタンプで結果が安定しない(毎回同じ結果にならない)とかかなあ…と思ったりしました。

```
$ruby test/ls_test.rb
Run options: --seed 5855

# Running:

.....F

Finished in 0.022102s, 271.4686 runs/s, 271.4686 assertions/s.

  1) Failure:
LsTest#test_ls_show_dotfiles [test/ls_test.rb:38]:
--- expected
+++ actual
@@ -1,2 +1,3 @@
-".                   dir_foobar          dummy_file_002.txt  dummy_file_004.txt  lorem_ipsum_10p.txt lorem_ipsum_2p.txt  symlink_file.txt
-..                  dummy_file_001.txt  dummy_file_003.txt  dummy_file_005.txt  lorem_ipsum_1p.txt  lorem_ipsum_5p.txt"
+".                   dummy_file_001.txt  dummy_file_004.txt  lorem_ipsum_1p.txt  symlink_file.txt
+..                  dummy_file_002.txt  dummy_file_005.txt  lorem_ipsum_2p.txt
+dir_foobar          dummy_file_003.txt  lorem_ipsum_10p.txt lorem_ipsum_5p.txt"


6 runs, 6 assertions, 1 failures, 0 errors, 0 skips
```

2021-02-10 03:01 UTC, ksmxxxxxx commented
> > Did
> 
> Did What? という気持ちになったのですが、どこかで見かける言い回しでしょうか…。「Did not do」も同様で「やってません!」っていう印象を受けました。感性の問題かな…。特に代案もないのですが…。
> 
> > ↑macOS
> 
> スクショを貼り忘れているのかも?
> 
> > * Rubocopに注意されたけど、どう書き直したものかがわからなかった
> 
> * rubocopの実行結果があれば教えてください(スクショよりはターミナルへの出力結果がよさそう)
> * .rubocop.yml もあるとうれしいです(どういう設定にもとづいた警告だったのかがわかると参考になりそう)

- 見出しに関しては日本語に修正しました
- スクショについては一枚でまとめて貼っていたのですが分かりづらかったようなのでmacOSのlsとrubyのlsで分けました
- Rubocopについては `fjord/rubocop`を使っていて、それについてくるyamlを使ってるものを参照しています。リポジトリのrootに入ってると思います。
- Rubocopで怒られてる部分のメッセージは「`Style/StringConcatenation: Prefer string interpolation to string concatenation.`」でした。実行結果は以下です

```
% rubocop lib/show.rb                                                                                                                                      ls_command_oop ✭ ◼
Inspecting 1 file
C

Offenses:

lib/show.rb:21:7: C: [Correctable] Style/StringConcatenation: Prefer string interpolation to string concatenation.
      file.filetype_permission.ljust(filetype_permission_column_width, ' ') + ...
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected, 1 offense auto-correctable
```

## テストについて
もしかするとターミナルの幅が自分の環境と違うせいでファイルの並びが`expected`と違う並びになることでひかかってるのかもしれないと予想しました。
テストとして、ターミナルの幅を考慮しない書き方をしてなかったので良くなかったなぁって思ってるところです。
`-l`オプションのテストみたいに、expectedにオリジナルのlsコマンドの結果を参照するように書き換えるのが良いのかなと考えました。

2021-02-10 04:16 UTC, kakutani commented
対応やコメントありがとうございます。とりいそぎ、言及されていないテストの観点について。

> test/fixtures/dir_foobar

の作成をテストコードでやるか、リポジトリにpushしておくか、いずれにせよpullしたユーザーがテスト実行でうまく動いていることを確かめられるようにする必要があると思います。

2021-02-10 04:17 UTC, kakutani commented
> * Rubocopについては `fjord/rubocop`を使っていて、それについてくるyamlを使ってるものを参照しています。リポジトリのrootに入ってると思います。

なるほど〜 👀 
これなら手元でもたしかめられそうですね(`.rubocop.yml`が無いぞ…ととまどっていた)。
丁寧な説明ありがとうございます。

2021-02-10 04:29 UTC, ksmxxxxxx commented
> test/fixtures/dir_foobar
> の作成をテストコードでやるか、リポジトリにpushしておくか、いずれにせよpullしたユーザーがテスト実行でうまく動いていることを確かめられるようにする必要があると思います。

ごめんなさい、こちらてっきり`dir_foobar`ディレクトリはコミットされてるものだと思っていました。
リポジトリにpushする形で対応しました。

1922351

2021-02-10 09:07 UTC, kakutani commented
動作を確認できました。実務に近い考えかたでいくと、まずはテストがパスするように修正してもらえると助かります!

私のほうでも見てみますが、私からのフィードバックを待たずに、まずは修正する作戦を考えてみてください。

2021-02-10 13:49 UTC, ksmxxxxxx commented
d2d0490

テストが落ちる件、今の段階で「本家lsコマンドの実行結果をexpectedにしてテストする」方法でいい手が思いつかないので、テストをskipするようにしました。

（commit commentを英語で書いてるのは、前職で「英語で書け」って言われた時の名残と、自分の英語勉強の一環です）（語彙が貧困 + 文法が不得意なので突っ込みどころあったら突っ込んでください）

2021-02-13 02:45 UTC, kakutani requested changes
まずは `Ls.new.call` だけ読みました。

2021-02-13 02:45 UTC, kakutani commented on 08.ls_object/lib/filelist.rb
> +require './lib/filedata'
`require_relative 'filedata'` で良さそう。

2021-02-13 02:45 UTC, kakutani commented on 08.ls_object/lib/ls.rb
> +require './lib/filedata'
`require_relative 'filedata'` で良さそう。

2021-02-13 02:45 UTC, kakutani commented on 08.ls_object/lib/ls.rb
> +require './lib/filelist'
`require_relative`(ry

2021-02-13 02:45 UTC, kakutani commented on 08.ls_object/lib/ls.rb
> +require './lib/show'
`require_relative`(ry

2021-02-13 02:45 UTC, kakutani commented on 08.ls_object/lib/ls.rb
> +  def options_parse
`private` で良さそう。メソッド名は動詞がよさそう。`parse_options`

2021-02-13 02:45 UTC, kakutani commented on 08.ls_object/lib/ls.rb
> +    option = options_parse
ここは `options` が適切そう。

2021-02-13 02:45 UTC, kakutani commented on 08.ls_object/lib/ls.rb
> +    return print "ls: #{ARGV[0]} : No such file or directory" unless File.exist?(ARGV[0] || '.')
`ARGV[0]`を3回使っているので、名前をつけたほうがよさそう。
`ARGV[0] || '.'` となるとカレントディレクトリが存在しない場合ってあるのかな…(わからない)。

`target = ARGV[0] || '.'` みたいに初期化しているということであれば、デフォルトをカレントディレクトリに設定しているのだな、という意図はわかります。そのあとに、 `unless File.exist?(target)` としているのなら、そこでの意図は明確なので気にならないです。

が、現状だと「引数が指定されていない場合にはカレントディレクトリの存在を確認する」というコードになっているので、違和感をおぼえます。

2021-02-13 02:45 UTC, kakutani commented on 08.ls_object/lib/ls.rb
> +  def short_format
`private`

2021-02-13 02:45 UTC, kakutani commented on 08.ls_object/lib/ls.rb
> +  def long_format
`private`

2021-02-13 02:45 UTC, kakutani commented on 08.ls_object/lib/ls.rb
> +    @show = Show.new(ARGV[0])
`Show`って名詞も自動詞も他動詞もあるので、「表示」という名詞的な意図なら別の名前のほうがいいかもなあと思いました。

2021-02-13 06:09 UTC, ksmxxxxxx commented on 08.ls_object/lib/filelist.rb
> +require './lib/filedata'
7cb5900

2021-02-13 06:09 UTC, ksmxxxxxx commented on 08.ls_object/lib/ls.rb
> +require './lib/filedata'
7cb5900

2021-02-13 06:09 UTC, ksmxxxxxx commented on 08.ls_object/lib/ls.rb
> +require './lib/filelist'
7cb5900

2021-02-13 06:09 UTC, ksmxxxxxx commented on 08.ls_object/lib/ls.rb
> +require './lib/show'
7cb5900

2021-02-13 06:09 UTC, ksmxxxxxx commented on 08.ls_object/lib/ls.rb
> +  def options_parse
56154ad

2021-02-13 06:10 UTC, ksmxxxxxx commented on 08.ls_object/lib/ls.rb
> +  def short_format
56154ad

2021-02-13 06:10 UTC, ksmxxxxxx commented on 08.ls_object/lib/ls.rb
> +  def long_format
56154ad

2021-02-13 06:10 UTC, ksmxxxxxx commented on 08.ls_object/lib/ls.rb
> +  def options_parse
8e75552

2021-02-13 06:10 UTC, ksmxxxxxx commented on 08.ls_object/lib/ls.rb
> +    option = options_parse
8e75552

2021-02-13 06:13 UTC, ksmxxxxxx commented on 08.ls_object/lib/ls.rb
> +    return print "ls: #{ARGV[0]} : No such file or directory" unless File.exist?(ARGV[0] || '.')
51de462

`'.'`は設定していないと動かないので、`target`で`ARGV[0]`とセットで初期化するようにしました。

2021-02-13 06:24 UTC, ksmxxxxxx commented on 08.ls_object/lib/ls.rb
> +    @show = Show.new(ARGV[0])
コメントの意図を確認したいのですが、他のクラスで`FileList`や`FileData`という名詞に対して、`Show`だけ自動詞や他動詞も含む単語だから名詞にしたほうが良さそうっていう意図かなって解釈したんですが、合ってますかね？

もしそうであれば、`Display`が適当なのかなと考えました。

2021-02-13 06:49 UTC, ksmxxxxxx commented on 08.ls_object/lib/ls.rb
> +    @show = Show.new(ARGV[0])
e742878

名前を変更したcommitを追加しました

2021-02-13 10:01 UTC, kakutani commented on 08.ls_object/lib/ls.rb
> +    @show = Show.new(ARGV[0])
> `Show`だけ自動詞や他動詞も含む単語だから名詞にしたほうが良さそうっていう意図かなって解釈したんですが、合ってますかね？

遅れましたが、意図はそうです。ここは`Display`で良さそうです。

ちなみに、個人的には動詞っぽいクラス名も「アリ」かなーとは思っています。が、ここで`Show`だと「Show, what?」という気持ちになったので、`Display`で良いと思います。

2021-02-13 10:04 UTC, kakutani commented on 08.ls_object/lib/ls.rb
> +    return print "ls: #{target} : No such file or directory" unless File.exist?(target)
コードがすっきりしたら別のことが気になりました。ターゲットがなければ、これはうまく動かないっていうことだから、エラー扱いでよさそう。

```suggestion
    raise "ls: #{target} : No such file or directory" unless File.exist?(target)
```

こちらのほうが意図に近いのでは?

2021-02-13 10:08 UTC, kakutani commented on 08.ls_object/lib/ls.rb
> +    display.list_reverse if options.key?(:r)
ここだけ後置`if`になっているのが気になるけれど、まあ仕方ないか…。
並び替えは明示的にするようにしておけば、

```ruby
if options.key?(:r) ? display.list_reverse : display.sort
```

みたいにできるかもしれないですね(まだ`Display`は読んでいませんが…)

2021-02-13 12:11 UTC, kakutani commented
これもふと気づいていしまったのですが、
`lib/ls.rb` は実行させるコマンドなので、`bin/ls.rb` に置いたほうが「それっぽい」かもしれませんね。
`bin/ls_rb` みたいな実行コマンド名にして、そこから `lib/lr.rb` を`require_relative`で読み込んで実行する、というのでもいいかもしれません。

私ならそうするかなあ、という程度なので対応必須というわけではありません。

2021-02-13 12:20 UTC, kakutani commented on 08.ls_object/lib/ls.rb
> +    display.list_reverse if options.key?(:r)
`FileList`で`Dir.glob`した結果を`sort`していますね。`sort`するのは表示のためのものなら、明示的に`sort`するのはこのタイミングでもよいかもしれません。現状は、`FileList`で考えかたとして`sort`は1箇所でいいはずなのに、2箇所に`sort`が書いてありますね。

'FileList#contain_dotfile`と`FileList#without_dotfile`の名前から想像できる役割は「dotファイル込みでリストを取得するのかどうか」だと思うのですが、現状は「取得したファイル群を並び替える」という役割も担ってますね。

2021-02-13 12:35 UTC, kakutani commented on 08.ls_object/lib/display.rb
> +    files.reverse!
破壊的な操作であることが呼び出し元からはわからなくなっているのですね。`FileList`の`sort`のところと合わせて、整理しなおすといいかもしれません(`sort`のほうでは破壊的には並び替えていませんでした)。

2021-02-13 12:39 UTC, kakutani commented on 08.ls_object/lib/filedata.rb
> +    if updated_at.strftime('%Y-%m-%d') <= Date.today.prev_month(6).strftime('%Y-%m-%d')
6ヶ月以上前の更新日かどうかで表示書式を切り分ける仕様を実現するチャレンジは良いですね。

ただ、条件節の比較が「文字列の大小」になっているようです。
ここでの意図は、ファイル更新日時が現在日時の半年以上前かどうかだと思います。
(文字列が大きい小さいとは??)

`File#mtime`の戻り値は`Time`のインスタンスなので、`Tiime`が半年以上前の`Time`よりも古いかどうかで判別するほうがよさそうです。

2021-02-13 12:44 UTC, kakutani commented
`Display` で `private` なものと`public`なものを分けてもらえると読み進めやすくなりそうです。

Rubyでは厳密に`private`とそうじゃないものを分けるべし、という規則は無いのですが、
メソッド数も多くて、読み進めていくうえで行ったり来たりが多いなあと感じました。

2021-02-13 12:49 UTC, kakutani commented on 08.ls_object/lib/filedata.rb
> +  attr_reader :target, :file, :fs, :type, :mode, :nlink, :uid, :gid, :size, :updated_at, :blocks
`:fs` はコンストラクタの中でしか使ってないので、`attr_reader`として他のオブジェクトから読み出せるようにする必要はなさそう。

自己カプセル化フィールドとして`private def fs; @fs end`みたいなのを定義してもいいけど、そこまでやらなくてもいいかな…。

`@fs`で十分、というか`fs`はローカル変数でもよさそう。

2021-02-13 12:50 UTC, kakutani commented on 08.ls_object/lib/filedata.rb
> +      "#{file} -> #{File.readlink("#{target}/#{file}")}"
L6の`"#{target}/#{file}"`と重複していますね。インスタンスとして管理しておいてよい情報かもしれません。

2021-02-13 12:55 UTC, kakutani commented on 08.ls_object/lib/filelist.rb
> +    files.map { |file| FileData.new(target, file) }
Ruby(以外の言語でもそうですが)だと、`File`というクラスやオブジェクトもあるので、ここで扱っているのは「ファイルの名前」だと思います。`name`, `file_name`,  `fname`(よく使われる略称) あたりのほうがいいかもしれません(`FileDate`でも`file`よりは名前であることを明示したほうがよさそう)。

また、`target`って何のターゲットかなあ…という気持ちになったのですが、ここでは「表示対象となるディレクトリ名」だから`dirname`とかのほうがわかりやすいかも、と思いました。

`FileData.new(dirname, fname)` のほうが意図がよく伝わりそう、と思ってます。

2021-02-13 13:01 UTC, kakutani commented on 08.ls_object/lib/filedata.rb
> +    }
`permission_converting_code`の中身は変わらないので、定数としてもよさそうです。
現状だと`permission`が呼び出されるたびにhashが作られて、呼び出しが終わったら破棄されます。

2021-02-13 13:02 UTC, kakutani commented on 08.ls_object/lib/filedata.rb
> +    }
`file_type_converting_code`も定数でよさそうですね。

2021-02-15 03:55 UTC, kakutani commented on 08.ls_object/lib/filedata.rb
> +    filetype + permission
初見では `filetype` に `permission` を加算して何をしているのかな…? と思ったのですが、これは文字列を組み立てているのですね。
であれば:
`"#{filetype}#{permission}"` とstring interpolation(式展開)を使ったほうが意図はわかりやすいです。

2021-02-15 03:59 UTC, kakutani commented on 08.ls_object/lib/filedata.rb
> +    permission_converting_code[owner] + permission_converting_code[group] + permission_converting_code[user]
ここも数値の操作かな…と思っていたのですが、文字列なのですね。
実は繰り返し処理として扱えたりしないでしょうか。

2021-02-15 13:27 UTC, ksmxxxxxx commented on 08.ls_object/lib/filedata.rb
> +    }
57c2c5e

2021-02-15 13:28 UTC, ksmxxxxxx commented on 08.ls_object/lib/filedata.rb
> +    }
57c2c5e

2021-02-15 14:58 UTC, ksmxxxxxx commented on 08.ls_object/lib/filedata.rb
> +    permission_converting_code[owner] + permission_converting_code[group] + permission_converting_code[user]
0fce992

2021-02-15 14:59 UTC, ksmxxxxxx commented on 08.ls_object/lib/filedata.rb
> +    filetype + permission
83e5219

2021-02-15 15:05 UTC, ksmxxxxxx commented on 08.ls_object/lib/filelist.rb
> +    files.map { |file| FileData.new(target, file) }
ec8302cb29167698e49081ba7ea84f5255b4dc37

2021-02-15 15:14 UTC, ksmxxxxxx commented on 08.ls_object/lib/filedata.rb
> +      "#{file} -> #{File.readlink("#{target}/#{file}")}"
d5dcd16

2021-02-15 15:21 UTC, ksmxxxxxx commented on 08.ls_object/lib/filedata.rb
> +  attr_reader :target, :file, :fs, :type, :mode, :nlink, :uid, :gid, :size, :updated_at, :blocks
008261e

2021-02-15 15:42 UTC, ksmxxxxxx commented on 08.ls_object/lib/filedata.rb
> +    if updated_at.strftime('%Y-%m-%d') <= Date.today.prev_month(6).strftime('%Y-%m-%d')
8ce8ba9

あ、、、Dateオブジェクトで比較する変更にしてしまった…Timeオブジェクトでもできるんですね…

2021-02-16 09:16 UTC, kakutani commented on 08.ls_object/lib/filedata.rb
> +  }
`}.freeze` (実効性よりは「定数です」という気持ちみたいなものですが)

2021-02-16 09:16 UTC, kakutani commented on 08.ls_object/lib/filedata.rb
> +  }
`}.freeze` (実効性よりは「定数です」という気持ちみたいなものですが)

2021-02-16 09:16 UTC, kakutani commented on 08.ls_object/lib/filedata.rb
> +  }
特に決まりはありませんが、定数は `attr_reader` (クラスメソッド) よりも前に宣言するのがいいかなあと思いました。

2021-02-16 09:16 UTC, kakutani commented on 08.ls_object/lib/filedata.rb
> +  }
特に決まりはありませんが、定数は `attr_reader` (クラスメソッド) よりも前に宣言するのがいいかなあと思いました。

2021-02-16 09:16 UTC, kakutani commented on 08.ls_object/lib/filedata.rb
> +    if updated_at.to_date <= Date.today.prev_month(6)
すっきりすると、さらにすっきりさせたくなりますね。

```ruby
def date
  time_or_year = older_than_months(6)? ? ' %Y' : '%H:%M'
  updated_at.strftime("%_m %_d #{time_or_year}")
end
...
private
def older_than_months?(m)
  updated_at.to_date <= Date.today.prev_month(m)
end
```

`#date`の意図としてはこんな感じでは、と思いました。
コードを短くする、という観点だと、さらに短く:

```ruby
  updated_at.strftime("%_m %_d #{older_than_months(6)? ? ' %Y' : '%H:%M'}")
```
ともできますが、個人的にはやりすぎかなーという気持ちになる(意図がメソッド呼び出しのなかにネストして埋もれてしまう。

2021-02-16 11:53 UTC, ksmxxxxxx reviewed
まだ途中ですが、一旦ここでsubmit review.

2021-02-16 11:53 UTC, ksmxxxxxx commented on 08.ls_object/lib/ls.rb
> +    return print "ls: #{target} : No such file or directory" unless File.exist?(target)
7310e20

意図としては確かに例外を出したほうがいいのかなと思う一方で、プラクティスとしては本家の見た目に近づけるというのが合ったと思うので、`return print~`としていました。

`raise`を返したときの表示でなるべく本家に近い形を目指して、現状は以下の表示になっています。

```zsh
❯❯❯ % ruby lib/ls.rb -l hoge  
lib/ls.rb:20:in `ls': hoge is no such file or directory (ArgumentError)
	from lib/ls.rb:52:in `<main>'
```

こっちは本家
```zsh
❯❯❯ % ls -la hoge 
ls: hoge: No such file or directory
```

2021-02-16 11:53 UTC, ksmxxxxxx commented on 08.ls_object/lib/display.rb
> +    files.reverse!
6798de5

2021-02-16 11:53 UTC, ksmxxxxxx commented on 08.ls_object/lib/ls.rb
> +    display.list_reverse if options.key?(:r)
6798de5

コメントの意図をちゃんと理解できてるか、少し自信がないのですが…「つまりこういうことかな」っていう感じにしてみました

2021-02-16 12:20 UTC, ksmxxxxxx commented on 08.ls_object/lib/filedata.rb
> +  }
b9d9d1a

2021-02-16 12:20 UTC, ksmxxxxxx commented on 08.ls_object/lib/filedata.rb
> +  }
b9d9d1a

2021-02-16 12:21 UTC, ksmxxxxxx commented on 08.ls_object/lib/filedata.rb
> +    if updated_at.to_date <= Date.today.prev_month(6)
3f8e848

引数は 👮🏻‍♂️ に怒られるので`month`にしてます

2021-02-16 12:23 UTC, ksmxxxxxx commented
> Display で private なものとpublicなものを分けてもらえると読み進めやすくなりそうです。

26584f5
ca204d7
ee9205f

分かる範囲でやってみました。

2021-02-16 12:27 UTC, ksmxxxxxx commented
@kakutani コメントを頂いたところ、一通り手を加えてみました。

そろそろ長くなってきて確認が辛くなってきてるので、OKってところ、確認したってところは`Resolve`押してくれると 🙏🏻

2021-02-16 12:33 UTC, ksmxxxxxx commented
(´-`).oO見てもらったら一回rebaseしよう……

2021-02-16 12:40 UTC, kakutani approved these changes
確認しましたー

2021-02-16 12:49 UTC, kakutani approved these changes
あとからまた追加でレビューしちゃってた場合、先に出したぶんだけapproveしてもいいんだっけ…。

2021-02-16 12:52 UTC, kakutani approved these changes

2021-02-16 13:12 UTC, kakutani commented on 08.ls_object/lib/ls.rb
> +    return print "ls: #{target} : No such file or directory" unless File.exist?(target)
課題の意図からすると例外が抜けていっても良いと思いますが、「本家に近い形」を目指すのだととすると、`print`で抜けると正常終了なので行儀はよくなさそうです。

ちゃんと試してませんが呼び出す側から、

```ruby
begin
  puts Ls.new.ls
rescue ArgumentError => e
  puts e.message
  exit 1
end
```
とすると、`ls`の挙動に近くなりそうです。

2021-02-16 13:32 UTC, kakutani commented on 08.ls_object/lib/ls.rb
> +require_relative 'filedata'
`require_relative`するのは直接使っているものだけにしてください。

2021-02-16 13:32 UTC, kakutani commented on 08.ls_object/lib/ls.rb
> +require_relative 'filelist'
`require_relative`するのは直接使っているものだけにしてください(ls.rbからは使っていない)

2021-02-16 14:04 UTC, kakutani commented
> そろそろ長くなってきて確認が辛くなってきてるので、OKってところ、確認したってところは`Resolve`押してくれると 🙏🏻

`Resolve conversation`のボタンが見あたらないなー、と思ってHideをポチポチしたり、Reviewをapproveしたりしていたのですが:

> You can resolve a conversation in a pull request if you opened the pull request or if you have write access to the repository where the pull request was opened.

とのことなので、 私は ksmxxxxxx/ruby-practices のリポジトリでの権限が足りないみたいですね。
メンターにResolveさせたかったら、PRをオープンする権限を与える必要がありそうです。

2021-02-16 14:06 UTC, kakutani commented
@ksmxxxxxx 解決したと思うやつはhide commentしておいたので、お手すきでResolveしておいてもらえればと思います。

2021-02-16 14:29 UTC, kakutani commented
> (´-`).oO見てもらったら一回rebaseしよう……

このPRにforce pushすると議論の履歴が吹き飛んじゃうので、ここまでの会話を仕切り直したいのであれば、このPRを一旦closeして別PRを開き直すほうがいいかなと思いました。

2021-02-16 14:32 UTC, ksmxxxxxx commented
> > (´-`).oO見てもらったら一回rebaseしよう……
> 
> このPRにforce pushすると議論の履歴が吹き飛んじゃうので、ここまでの会話を仕切り直したいのであれば、このPRを一旦closeして別PRを開き直すほうがいいかなと思いました。

会話の仕切り直しというより、fixupのcommitをfixupしたいかなぁって思ったくらいです。
そういう場合も議論の履歴って吹っ飛んじゃうんでしたっけ？ 🤔

2021-02-16 14:38 UTC, kakutani commented
> そういう場合も議論の履歴って吹っ飛んじゃうんでしたっけ？ 🤔

レビューの途中でrebaseするみたいな高度な使いかたを自分ではやらないので、お任せします!
(私じしんはぐちゃっとコミットを潰された経験しかしたことないので…)

2021-02-17 00:56 UTC, kakutani commented on 08.ls_object/lib/filedata.rb
> +  end
これぐらいなら三項演算子でもよさそう。

```ruby
def name_or_symlink
  type == 'link' ? "#{file} -> #{File.readlink(@file_path)}" : file
end
```

```ruby
private
def symlink_dest
  File.readlink(@file_path)
end
```
とすれば、
```ruby
def name_or_symlink
  type == 'link' ? "#{file} -> #{symlink_dest}" : file
end
```
と書けるので、`name_or_symlink`っぽさはさらに出ますが、そこまでやらなくてもいいか…。

2021-02-17 01:02 UTC, kakutani commented on 08.ls_object/lib/display.rb
> +      # ↓ここrubocop先生に怒られてるけど、どうなおしていいもんなのかがわからなかった
文字列を連結しているから怒られていそう(確かにパフォーマンスにいくらか影響はあります)。
ブロックの処理の固まりが大きいので、まず、privateメソッドに括り出しましょうか。
`long_format_of(file)`とかそんな感じですかね…(名前はテキトウです)。

現状は文字列を`+`で連結しているので、`[file.filetype...,file.nlink...,file.uid...].join`と配列にして`join`すれば警告はされなくなるんじゃないかなあと思います。

2021-02-17 01:05 UTC, kakutani commented on 08.ls_object/lib/display.rb
> +  # **_column_width、同じことをしているので、`column_width(method)`みたいなメソッドにしていい感じにしたかった
```ruby
def colum_with(attr_sym)
  files.map{ |file| file.send(attr_sym).length }.max
end
```

でいけますかね。

2021-02-17 01:21 UTC, kakutani commented
24文字の長さのファイル名があるディレクトリで実行したら例外が発生しました。

![image](https://user-images.githubusercontent.com/2160/108142786-cb09e600-7109-11eb-9f96-2defd5561ed7.png)

2021-02-17 02:13 UTC, ksmxxxxxx commented
rebase ed.

2021-02-17 02:44 UTC, ksmxxxxxx commented on 08.ls_object/lib/ls.rb
> +require_relative 'filedata'
123859b

2021-02-17 02:44 UTC, ksmxxxxxx commented on 08.ls_object/lib/ls.rb
> +require_relative 'filelist'
123859b

2021-02-17 02:50 UTC, kakutani reviewed
`long_format`あたりを読みました。

2021-02-17 02:50 UTC, kakutani commented on 08.ls_object/lib/display.rb
> +  attr_reader :list, :files
`list`や'files`は他のオブジェクトに見せていない属性のようなので、`attr_reader`じゃないほうがよさそうです。

2021-02-17 02:50 UTC, kakutani commented on 08.ls_object/lib/ls.rb
> +    display.list_file_stat
`list_file_stat` してからじゃないと `long_format` できない、という呼び出し順の知識は`Display`の外に出さなくてもよさそうです。`Display#long.format`の中で呼び出せばよさそう。となると、`long_format`は1行だけのメソッドになりそうで、そうなるとメソッドとしての情報量がほとんどなくなってしまうので、インライン化してよさそう。

2021-02-17 02:50 UTC, kakutani commented on 08.ls_object/lib/filelist.rb
> +  attr_reader :dirname, :files
`dirnames`も`files`も`FileList`の外には出していない情報なので、`attr_reader`しなくてよさそうです。

2021-02-17 02:50 UTC, kakutani commented on 08.ls_object/lib/filelist.rb
> +  def file_stat
`file_stats`のほうがよさそう(配列なので)

2021-02-17 02:50 UTC, kakutani commented on 08.ls_object/lib/display.rb
> +      file.filetype_permission.ljust(filetype_permission_column_width, ' ') +
ここって filetype と permission を並べているから長さは固定だと思います。
`ljust`しても空白が詰まることはないので、あえて複雑なことをする必要はなさそうです。

2021-02-17 02:50 UTC, kakutani commented on 08.ls_object/lib/display.rb
> +  # **_column_width、同じことをしているので、`column_width(method)`みたいなメソッドにしていい感じにしたかった
名前は `column_max_width` が意図に近そうですね。

2021-02-17 02:50 UTC, kakutani commented on 08.ls_object/lib/display.rb
> +        file.date.rjust(date_column_width, ' ') + ' ' +
`date` といいつつ日付以外にも、日付時刻で表示しているから悩ましいですね…。`timestamp` ぐらいの言葉にしておくほうが無難かな…。lsのヘルプを見ると`last_modified`あたりが無難そう。

2021-02-17 02:58 UTC, ksmxxxxxx commented on 08.ls_object/lib/filedata.rb
> +  end
2a30079

`dest`っていう略語が自分には「？」という感じだったんで `destnation`にしました（そんな長ったらしいものでもないと思いま 🍣 ）

2021-02-17 03:28 UTC, kakutani reviewed
`short_format` を読みました。

2021-02-17 03:28 UTC, kakutani commented on 08.ls_object/lib/display.rb
> +    row_length = max_name_length * column_count
`row` は一般的に「行」なのですが、ここで求めているのは「カラム(桁)の長さ」ですよね? (`column_length`?)

2021-02-17 03:28 UTC, kakutani commented on 08.ls_object/lib/display.rb
> +    column_line_count <= 1
ここは 1 より小さくなることは無さそうです。'column_line_count == 1` 

あと、`column_line_count` っていう名前がちょっと難しかったです。
「(表示するエントリの数)  / (カラム数)」は、「表示のために必要な行数」かなあと思いました。

2021-02-17 03:28 UTC, kakutani commented on 08.ls_object/lib/ls.rb
> +    display.one_liner? ? display.short_format : display.short_format_split_into_columns
1行で流して表示するのか、カラムに整形して表示するのかの知識は`Display`にあるので、`long_format'と同様に、これは 'Display#soft_format` メソッドの責務ではないかなあと思いました(`Ls#shoft_format`は不要になりそう)。

2021-02-17 03:28 UTC, kakutani commented on 08.ls_object/lib/display.rb
> +    files.map { |f| f.ljust(max_name_length, ' ') }.join(' ')
`f.ljust(max_name_length, ' ')` 最大ファイル名の長さでスペース詰めする処理は重複しているから、まとめられるとよさそうですね。

2021-02-17 03:28 UTC, kakutani commented on 08.ls_object/lib/display.rb
> +    rows = files.each_slice(column_line_count).map { |f| f }
```suggestion
    rows = files.each_slice(column_line_count).to_a
```
何もしてないみたいなので。

2021-02-17 03:28 UTC, kakutani commented on 08.ls_object/lib/display.rb
> +    return unless rows.last.count <= column_line_count
後置`unless`は解釈がむずかしいので、よほど簡単でなければ後置`if`にしてください。
「最終行の数がカラム行数以下ではない」…ええと、つまり?? となりました。

また、ここで`return`するケースに該当すると `nil` が返りそうですが、呼び出し元ではそのまま `map`していますね。このケースに該当するのはどんな場合でしょう??

2021-02-17 03:28 UTC, kakutani commented on 08.ls_object/lib/display.rb
> +    count = column_line_count - rows.last.count
`transpose`しやすくできるように、最後の行で数を合わせていると思うのですが、注意ぶかく読み込まないといけないなあと思いました…。

* count: 「回数」← 何の?
* column_line_count: カラム行の数 ... いまは読み込んでいるからわかる
* rows.last.count: 最終行の数 ← 何の数だっけ?

「回数 = カラム行の数 - 最終行の数」

わかるようなわからないような、という気持ちでした。むずかしいですね。

2021-02-17 03:31 UTC, kakutani commented on 08.ls_object/lib/display.rb
> +    row_length = max_name_length * column_count
ローカル変数なので `cols_length` でもいいかも

2021-02-17 03:36 UTC, kakutani commented on 08.ls_object/lib/display.rb
> +    column_line_count <= 1
`Display`のpublicメソッドIではなく、`short_format`の内部処理で十分となれば、わざわざメソッドにしなくてもいいかもしれませんね。

2021-02-17 04:03 UTC, ksmxxxxxx commented on 08.ls_object/lib/display.rb
> +      # ↓ここrubocop先生に怒られてるけど、どうなおしていいもんなのかがわからなかった
まずは配列で文字列を連結するようにしてみました

bec43f8

2021-02-17 04:15 UTC, ksmxxxxxx commented on 08.ls_object/lib/display.rb
> +      # ↓ここrubocop先生に怒られてるけど、どうなおしていいもんなのかがわからなかった
括りだしってこういうことかな……と 🤔 

027424b

名前に関してはテキトウですって言われたので、少し考えたんですが……他に良さそうな語彙が思い当たらなかったのでそのまま採用させてもらいました 🙏🏻

2021-02-17 04:36 UTC, kakutani commented on 08.ls_object/lib/filedata.rb
> +  end
略さなくても構わないですが、https://rurema.clear-code.com/3.0.0/class/FileUtils.html コンテキストによっては略しても構わない単語だと思っています。

2021-02-17 05:46 UTC, ksmxxxxxx commented on 08.ls_object/lib/display.rb
> +  # **_column_width、同じことをしているので、`column_width(method)`みたいなメソッドにしていい感じにしたかった
8fcad51

できました〜 ✨ 

`Object#public_send`でメソッド指定するときはSymbolなんですね…
（最初メソッド名そのまま渡してて…すごい時間を溶かしてしまった）

2021-02-17 06:11 UTC, kakutani commented on 08.ls_object/lib/filedata.rb
> +    end.join
`map`なので手続き(`do...end`)よりも式('{...}`のほうがよさそう。
すべて繋げると意図の説明がまったく無いので:

```suggestion
    octal_digits = mode.to_s(8)[-3, 3].chars
    octal_digits.map { |oct| PERMISSION_CONVERTING_CODE[oct.to_i] }.join
```

ぐらいは説明があってもよさそうです。

`PERMISSION_CONVERTING_CODE` が長いかもしれませんね。役割に照らすと、
`PERMISSION_LABELS`ぐらいでいいかもしれません。

```ruby
mode.to_s(8)[-3, 3].chars.map { |oct| PERMISSION_LABELS[oct.to_i] }.join
```

短いけど、読み下すのがしんどそうですね。

```ruby
mode.to_s(8)[-3, 3].chars
  .map { |oct| PERMISSION_LABELS[oct.to_i] }.join
```

ともできますが、こうするなら、`octal_digits`変数を導入した版と大差なさそう(2行)。

定数のキーを、 `{0 => '---',...}`ではなくて、`{ '0' => '---',...}` と明示的に文字列にすれば、`to_i`は不要になりますね。

2021-02-17 06:54 UTC, ksmxxxxxx commented on 08.ls_object/lib/filelist.rb
> +  def file_stat
384e868

2021-02-17 06:54 UTC, ksmxxxxxx commented on 08.ls_object/lib/filelist.rb
> +  attr_reader :dirname, :files
4e1d44d

2021-02-17 06:54 UTC, ksmxxxxxx commented on 08.ls_object/lib/ls.rb
> +    display.list_file_stat
f70edbc

2021-02-17 06:55 UTC, ksmxxxxxx commented on 08.ls_object/lib/display.rb
> +  attr_reader :list, :files
daf857b

2021-02-17 07:20 UTC, ksmxxxxxx commented on 08.ls_object/lib/display.rb
> +        file.date.rjust(date_column_width, ' ') + ' ' +
`column_width` => `column_max_width`
6b6254b

`date` => `last_modified`
12068ab

2021-02-17 07:21 UTC, ksmxxxxxx commented on 08.ls_object/lib/display.rb
> +      file.filetype_permission.ljust(filetype_permission_column_width, ' ') +
8667872

2021-02-17 09:09 UTC, ksmxxxxxx commented on 08.ls_object/lib/display.rb
> +    files.map { |f| f.ljust(max_name_length, ' ') }.join(' ')
重複してるっていうのは、`short_format`と`short_format_split_into_columns`で`ljust`してるところ、纏められるよねってことですかね？

2021-02-17 09:15 UTC, kakutani commented on 08.ls_object/lib/display.rb
> +    files.map { |f| f.ljust(max_name_length, ' ') }.join(' ')
はい。まったく同じ処理に見えたのですが、たまたま同じだけならいまのままでも大丈夫です。

2021-02-17 09:19 UTC, ksmxxxxxx commented on 08.ls_object/lib/display.rb
> +    rows = files.each_slice(column_line_count).map { |f| f }
cc6d30a

2021-02-17 09:19 UTC, ksmxxxxxx commented on 08.ls_object/lib/ls.rb
> +    display.one_liner? ? display.short_format : display.short_format_split_into_columns
62544b2

2021-02-17 09:20 UTC, ksmxxxxxx commented on 08.ls_object/lib/display.rb
> +    column_line_count <= 1
62544b2

2021-02-17 09:22 UTC, ksmxxxxxx commented on 08.ls_object/lib/display.rb
> +    row_length = max_name_length * column_count
7c7414f

2021-02-17 11:21 UTC, ksmxxxxxx commented on 08.ls_object/lib/display.rb
> +    return unless rows.last.count <= column_line_count
377d96f

ifで良さそうだったので修正しました
（自分でも改めて読んでてなんで`unless`にしてたのか思い出せなかったです…）

2021-02-17 12:08 UTC, ksmxxxxxx commented on 08.ls_object/lib/display.rb
> +    count = column_line_count - rows.last.count
b86acd8

こうしたらちょっとわかりやすいですかね？

2021-02-17 12:46 UTC, ksmxxxxxx commented on 08.ls_object/lib/filedata.rb
> +    end.join
c30ffd4
e20f585

2021-02-17 14:45 UTC, ksmxxxxxx commented on 08.ls_object/lib/display.rb
> +    files.map { |f| f.ljust(max_name_length, ' ') }.join(' ')
13535c5

2021-02-17 15:09 UTC, ksmxxxxxx commented on 08.ls_object/lib/ls.rb
> +    return print "ls: #{target} : No such file or directory" unless File.exist?(target)
dfc9a91

![image](https://user-images.githubusercontent.com/5976902/108223837-959ee000-717d-11eb-8646-b04a2ac54b5a.png)

✨

2021-02-18 01:50 UTC, kakutani commented on 08.ls_object/lib/display.rb
> +    return unless rows.last.count <= column_line_count
`if/unless`もそうですが、ここが評価されて `nil`で戻ったら、呼び出し元の`map`で落ちちゃいそうですけど、ここが成立する条件って、どういうものでしょう?(そしてそれはバグなのでは? という指摘でした)。

2021-02-18 02:01 UTC, kakutani commented
`PERMISSION_LABELS` に名前を変えると

```
FILETYPE_CONVERTING_CODE = {
  'file' => '-',
  'directory' => 'd',
  'link' => 'l'
}.freeze
```
これももうちょっと名前を短くできそうですね。
* ハッシュにキーを与えて引くことが変換だとすれば、`CONVERTING`は冗長そう
* `CODE`なのは、まあそれはそうだけど…という気持ち

私なら `FILETYPE_ABBREV` とかにするかなあ(Abbrev = Abbreviation)

(直したほうがいいというわけではなく、バランスが悪く見えてきたのでコメントしました)

2021-02-18 02:05 UTC, kakutani commented on 08.ls_object/lib/display.rb
> +    end.join("\n")
```suggestion
    files.map { |file| long_format_of(file)}.join("\n")
```

2021-02-18 02:12 UTC, kakutani commented on 08.ls_object/lib/ls.rb
> +    return print "ls: #{target} : No such file or directory" unless File.exist?(target)
豆知識です。

Unixプロセスには終了ステータスがあり([終了ステータス \- Wikipedia](https://ja.wikipedia.org/wiki/%E7%B5%82%E4%BA%86%E3%82%B9%E3%83%86%E3%83%BC%E3%82%BF%E3%82%B9))、`ls`も `ls -a hoge` としたら`1`を返します(zshなら `$?`に入ってます)。
```
$ls hoge; echo $?
ls: hoge: No such file or directory
1
```
正常終了は`0`です。

2021-02-18 02:14 UTC, kakutani commented on 08.ls_object/lib/display.rb
> +    count = column_line_count - rows.last.count
個人的には、かなりわかりやすくなりました。右辺のやっていることと左辺の名前を比べる手がかりができたので、読む負荷が下がりました。

2021-02-18 02:33 UTC, kakutani commented on 08.ls_object/lib/display.rb
> +  # ここらへん@filesに渡しまくってるけど、一瞬メソッドのレシーバを渡せばいいだけでは？って思ったけど、ls.rbのオプションでインスタンス変数（メソッド）に入ってくる中身が変わるので、このままでいいのかも知れないとおもったけどどうなんだろう…
このコメントの意図をいまいち汲み取れていないのですが、shortのときとlongのときで `@files`の配列の要素の型が異なるのですね(ここまで整理されて読み進めてやっと把握できた気がする)。

`@files`には:
* shortのとき: `Dir.glob`した結果である、ファイル名文字列の配列
* longのとき: `FileDate`の配列

Rubyでは変数はオブジェクトにつけている名前でしかないので、好きにできますが、
違うデータ構造(配列という意味では同じだが、入っているものの型が異なる)に同じ名前をつけると読み手が混乱します。
別の名前をつけて管理すると良さそうです。

(もっといえば、オプションがshortのときとlongのときで処理はかなりきれいに分かれそうなので、別のクラスにしてもいいかもしれないな、と思いましたが、まずは名前をそれぞれ別(たとえば`@files`と`@file_stats`)にしておいてもらえれば、よいです(クラスの再設計までは今回は求めません)。

2021-02-18 02:34 UTC, kakutani commented on 08.ls_object/test/ls_test.rb
> +require './lib/display'
`require_relative`を使ってください

2021-02-18 02:34 UTC, kakutani commented on 08.ls_object/test/ls_test.rb
> +require './lib/filedata'
このファイルでは直接使っていなさそう。

2021-02-18 02:34 UTC, kakutani commented on 08.ls_object/test/ls_test.rb
> +require './lib/filelist'
このファイルでは直接使っていなさそうなので削除。

2021-02-18 02:36 UTC, kakutani commented on 08.ls_object/lib/ls.rb
> +    raise(ArgumentError, "ls: #{target} is no such file or directory") unless File.exist?(target)
```suggestion
    unless File.exist?(target)
      raise(ArgumentError, "ls: #{target} is no such file or directory") 
    end
```
メッセージの組み立てが長くなっていたので、普通にブロックのほうがわかりやすそうです。

2021-02-18 12:32 UTC, ksmxxxxxx commented on 08.ls_object/lib/display.rb
> +    end.join("\n")
8f26ed6

2021-02-18 12:49 UTC, ksmxxxxxx commented on 08.ls_object/lib/display.rb
> +    return unless rows.last.count <= column_line_count
ごめんなさい、読み違えてました 🙏🏻 
今の実装だと、`rows.last.size`が`num_of_lines_needed`より小さい時`nil`が返って、`short_format_split_into_columns`の`map`で落ちちゃうよってことですね…
確かに 🐛 ですね

というわけで aabb47f で修正してみました

2021-02-18 13:27 UTC, kakutani commented on 08.ls_object/lib/display.rb
> +    return unless rows.last.count <= column_line_count
空白を詰めずに`transpose`すればよい、っていうことなのですね(いろんなバリエーションがあるんだろうけど想定できてないです、すみません)。

ちなみに、`if num_of_lines_needed > rows.last.size` が成立しないケース(空白を詰めなくて良いケース)ってどういうシチュエーションなのでしょう?
パッと思いつくのは、変換の後の列が表示したい列幅とぴったりそろっているときなのかなあ、と思ったのですが、不等号で判定してるしなーと思って細かい挙動までは追っていません 😅

2021-02-18 13:52 UTC, ksmxxxxxx commented on 08.ls_object/lib/display.rb
> +  # ここらへん@filesに渡しまくってるけど、一瞬メソッドのレシーバを渡せばいいだけでは？って思ったけど、ls.rbのオプションでインスタンス変数（メソッド）に入ってくる中身が変わるので、このままでいいのかも知れないとおもったけどどうなんだろう…
コメントが雑すぎましたね（すみません 💦 )

意図としては
- 同じ配列が入ってくるけどshortとlongで内容がちょっと違うから同じ `@files`使ってるのがなんとなく雑っぽくないかな…という迷い
- 単純に`@files`に代入してるメソッドが3つもあるけど、これって一般的な書き方なのかな？という疑問
という感じです。

> もっといえば、オプションがshortのときとlongのときで処理はかなりきれいに分かれそうなので、別のクラスにしてもいいかもしれないな、と思いましたが、まずは名前をそれぞれ別(たとえば@filesと@file_stats)にしておいてもらえれば、よいです(クラスの再設計までは今回は求めません)

まずはインスタンス変数だけ別にしておくのが良さそうなので、そのように修正してみます〜

2021-02-18 13:57 UTC, kakutani commented on 08.ls_object/lib/display.rb
> +  # ここらへん@filesに渡しまくってるけど、一瞬メソッドのレシーバを渡せばいいだけでは？って思ったけど、ls.rbのオプションでインスタンス変数（メソッド）に入ってくる中身が変わるので、このままでいいのかも知れないとおもったけどどうなんだろう…
> * 同じ配列が入ってくるけどshortとlongで内容がちょっと違うから同じ `@files`使ってるのがなんとなく雑っぽくないかな…という迷い

内容が「データの中身が違う(クラスの継承ツリーは同じ)」なら構いませんですが、こんかいは内容の「オブジェクトのクラスが違っている」なので、端的に言えば「雑」ですね。

言語仕様上は可能ですが、読み手に余計な認知負荷をかけることになります。

> * 単純に`@files`に代入してるメソッドが3つもあるけど、これって一般的な書き方なのかな？という疑問
>   という感じです。

これは場合によります。複数の方法でオブジェクトを初期化することはあり得ます。
が、こんかいでいえば役割が違うものを1つにまとめているからそうなっているんじゃないかなー、という印象です。

今回の対応としては、

> まずはインスタンス変数だけ別にしておくのが良さそうなので、そのように修正してみます〜

でよいと思います 🙆‍♂️

2021-02-18 14:05 UTC, ksmxxxxxx commented on 08.ls_object/lib/ls.rb
> +    raise(ArgumentError, "ls: #{target} is no such file or directory") unless File.exist?(target)
そうだなぁと思って試してみたんですが…… 👮🏻‍♂️ <「unless修飾子のほうがいいよ」と怒られてしまうんですよぇ

```ruby
    if File.exist?(target)
      @display = Display.new(target)

      options.key?(:a) ? display.list_contain_dotfile : display.list_without_dotfile
      options.key?(:r) ? display.list_reverse : display.list_sort
      options.key?(:l) ? display.long_format : display.short_format
    else
      raise(ArgumentError, "ls: #{target} is no such file or directory")
    end
```

としたら、今度は「ガード節を使い給へ」と指摘されました 🤔

2021-02-18 14:20 UTC, ksmxxxxxx commented on 08.ls_object/test/ls_test.rb
> +require './lib/display'
54344d8

ふと思ったんですが、 `require`と`require_relative`の使い分けってどのポイントになるんでしょう？ 🤔

2021-02-18 14:20 UTC, ksmxxxxxx commented on 08.ls_object/test/ls_test.rb
> +require './lib/filedata'
54344d8

2021-02-18 14:20 UTC, ksmxxxxxx commented on 08.ls_object/test/ls_test.rb
> +require './lib/filelist'
54344d8

2021-02-18 14:40 UTC, ksmxxxxxx commented on 08.ls_object/lib/display.rb
> +    return unless rows.last.count <= column_line_count
> ちなみに、if num_of_lines_needed > rows.last.size が成立しないケース(空白を詰めなくて良いケース)ってどういうシチュエーションなのでしょう?

指摘されて「そういえば変だわ…」って気がついたので修正したものが以下です

9a1e426

空白詰めなくていいケースは「`each_slice`した時に分割された配列が全部均等になっている」場合です。
均等になっていないと `transpose`でIndexErrorが返ってきてしまうからです。

[instance method Array\#transpose \(Ruby 3\.0\.0\)](https://rurema.clear-code.com/3.0.0/method/Array/i/transpose.html)

2021-02-18 14:45 UTC, ksmxxxxxx commented
https://github.com/ksmxxxxxx/ruby-practices/pull/2#issuecomment-778609464
https://github.com/ksmxxxxxx/ruby-practices/pull/2#issuecomment-780229028

この辺については、最後に対応したいと思います（というメモ）

2021-02-19 13:57 UTC, ksmxxxxxx commented on 08.ls_object/lib/display.rb
> +  # ここらへん@filesに渡しまくってるけど、一瞬メソッドのレシーバを渡せばいいだけでは？って思ったけど、ls.rbのオプションでインスタンス変数（メソッド）に入ってくる中身が変わるので、このままでいいのかも知れないとおもったけどどうなんだろう…
b67b13c

2021-02-22 14:57 UTC, ksmxxxxxx commented
> これもふと気づいていしまったのですが、
> `lib/ls.rb` は実行させるコマンドなので、`bin/ls.rb` に置いたほうが「それっぽい」かもしれませんね。
> `bin/ls_rb` みたいな実行コマンド名にして、そこから `lib/lr.rb` を`require_relative`で読み込んで実行する、というのでもいいかもしれません。
> 
> 私ならそうするかなあ、という程度なので対応必須というわけではありません。

こういう感じかなぁという変更を加えました。

23f448f

2021-02-22 16:02 UTC, ksmxxxxxx commented
> 24文字の長さのファイル名のファイルがあるディレクトリで実行したら例外が発生しました。
> (lsコマンドと、ls.rbの実行結果)
> 
> ![image](https://user-images.githubusercontent.com/2160/108142786-cb09e600-7109-11eb-9f96-2defd5561ed7.png)

f3c89c2

24文字以上のファイル名の考慮漏れでした 🙏🏻 
で、修正してみました。

`max_name_length`の長さにファイル名の後ろに付与されるスペースを考慮にいれてなかったので、まれにターミナル幅より`column_length`が`terminal_width`より小さくなってしまい、カラム数の計算をミスってしまう場合があったので、`(max_name_length + 1)`っていうのを追加しています。

もしかしたら`max_name_length` で `+ 1`したほうがいいかも？となってますが、いったんコレでcommitしました 🤔 

![image](https://user-images.githubusercontent.com/5976902/108734351-ba76c700-7572-11eb-98f7-3947a57cb2ef.png)

2021-02-23 14:02 UTC, ksmxxxxxx commented
916e972

テストを修正していますが、今回は自分の環境でチェックするのを目的に書いてるという前提にさせてほしいかなと思っています。
（日報で [こういうアドバイス](https://bootcamp.fjord.jp/reports/25493#comment_49574)もあったので…）

2021-02-28 14:39 UTC, komagata requested changes

2021-02-28 14:39 UTC, komagata commented on 08.ls_object/lib/display.rb
> +    files.count
`files.count`と`file_count`だと変わらないのでメソッドを定義しなくてもいいかも？です〜

2021-02-28 14:55 UTC, ksmxxxxxx commented on 08.ls_object/lib/display.rb
> +    files.count
対応しました〜

ef0a69d

2021-02-28 15:13 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-03-01 13:42 UTC, merged