[WIP] Write later
ksmxxxxxx/ruby-practices pull request #3
Opened 2021-03-03 03:51 UTC by ksmxxxxxx

# やったこと

- テストは書いてますが、あくまで自分環境向けに書いてます

# レビューしてほしいポイント

## スクリーンショット

2021-03-08 04:24 UTC, komagata requested changes

2021-03-08 04:24 UTC, komagata commented on 09.wc_object/lib/calc.rb
> +class Calc
クラス名は長くてもいいので略さない方がわかりやすいかもです〜

2021-03-08 04:24 UTC, komagata commented on 09.wc_object/lib/calc.rb
> +  def makeup_linecount_total
見た目を飾り立てるという意味であればデザインパターンにも出てくるdecorateという単語の方がいいかもと思いました。

2021-03-08 04:24 UTC, komagata commented on 09.wc_object/lib/display.rb
> +class Display
Displayなど一般的な単語なので他のプログラムと名前がぶつかる可能性が高いです。（しかし一般的な単語というのはいい名前ということです）なので、moduleを使ったnamespaceの中に全て納めてしまうのが良さそうです〜

2021-03-08 14:51 UTC, ksmxxxxxx reviewed
自分メモ用

2021-03-08 14:51 UTC, ksmxxxxxx commented on 09.wc_object/lib/read.rb
> +  def make_file_stratures
typo 💀

2021-03-09 05:35 UTC, komagata requested changes

2021-03-09 05:35 UTC, komagata commented on 09.wc_object/lib/calculation.rb
> +class Calculation
これやReadも名前が他のプログラムとぶつかりそうなので全部`Wc`のネームスペースの下に入れちゃうといいかもです〜。

moduleを使ったネームスペースは[オブジェクト指向プログラミング](https://bootcamp.fjord.jp/practices/211)にある参考のコードのgemとかを読むと書き方の参考になるかもです。

例えば、[sporkmonger/addressable](https://github.com/sporkmonger/addressable)とか。

gemなどほとんどの場合はgemの名前と同名のmodule=namespaceの下に全てのクラスを入れてます。（gemの名前は被らないことが担保されてるのでそれと同名のmoduleの下に入れれば必ず被らないので）

2021-03-09 06:19 UTC, komagata requested changes

2021-03-09 06:19 UTC, komagata commented on 09.wc_object/lib/read.rb
> +  class Read
クラス名は名詞が基本なのでReadだったらReaderとかの方がいいかもです〜

2021-03-09 11:22 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-03-09 12:31 UTC, merged